server:
  port: 8083              # Port sur lequel ton application écoute
  address: 0.0.0.0       # Écoute sur toutes les interfaces réseau

spring:
  application:
    name: my-spring-boot-app  # Nom de l'application

# Autres configurations nécessaires
# Par exemple, si tu utilises une base de données
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/your_database
#     username: your_username
#     password: your_password